### ISSUE TITLE
右键翻译的按钮位置放置在了错误的位置

### ISSUE THREAD

**Issue by QingFeng-awa** [MUKAPP/LiteLoaderQQNT-DeepL#10]
### QQNT版本
9.9.9-23159
### LiteLoaderQQNT
1.1.1
### 运行坏境
- 版本:Windows 11 专业版
- 版本:23H2
- 安装日期:‎2023.‎9.‎9
- 操作系统版本:22631.3527
### 期望的操作
右键点击消息,点击右键翻译功能。
### 实际的操作
1. 点击要翻译的消息,右键他弹出菜单。
2. 点击左下角更多,点击翻译。
### 日志信息
我找不到 _(不会找)_ 该插件的日志。
### 备注
该BUG在升级到LiteLoaderQQNT 1.1.x版本之后才会出现。
在LiteLoaderQQNT 1.0.x版本没有这个BUG。

**Comment by QingFeng-awa** [comment]
另外我看到了[与我提出的问题一致但状态为Closed的issues](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/issues/3)
但是在插件新版本(1.2.3)又出现了这个BUG。

**Comment by MUKAPP** [comment]
已修复
