### ISSUE TITLE
消息右键翻译选项消失

### ISSUE THREAD

**Issue by Starrain08** [MUKAPP/LiteLoaderQQNT-DeepL#11]
如题
QQNT版本
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/119772101/b2ee0d0e-04f4-4a2a-88b4-0b5bb4dce0f2)
故障表现
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/119772101/8bf09342-1448-4929-8a69-9a6a80d2b6b5)
LiteLoader版本
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/119772101/6416d6b4-a455-4cf8-820f-4affe9b5eb06)

**Comment by MUKAPP** [comment]
已修复
