### ISSUE TITLE
qq启动报错 ，请大佬救救孩子

### ISSUE THREAD

**Issue by ZeAn-an** [MUKAPP/LiteLoaderQQNT-DeepL#16]
<img width="416" alt="image" src="https://github.com/user-attachments/assets/06b102ef-5ad6-461f-abad-0c6f5e8b77cb">

**Comment by MUKAPP** [comment]
下载release里的版本，不要直接下载仓库

**Comment by ZeAn-an** [comment]
> 下载release里的版本，不要直接下载仓库

最新问题，一直转圈，就是不能翻译是为啥
