### ISSUE TITLE
翻译按钮位置错误

### ISSUE THREAD

**Issue by shi-an** [MUKAPP/LiteLoaderQQNT-DeepL#3]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/79352488/c14f8b19-ef0f-440e-9f1b-c2fe07e7987b)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/79352488/0aef0a9d-f82b-424b-a954-09c016923da8)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/79352488/8d2064dd-c305-47a7-8c64-14bc508c6662)
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/79352488/f098fc4d-9037-4e57-8d88-24693fda7561)

**Comment by MUKAPP** [comment]
已修复 https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/releases/tag/v1.0.6
