### ISSUE TITLE
macOS 上菜单位置错误

### ISSUE THREAD

**Issue by tiankaima** [MUKAPP/LiteLoaderQQNT-DeepL#6]
与 #3 类似, 没有出现在:
<img width="577" alt="图片" src="https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/ae95a56b-98ef-4c8f-b5d2-7d648832446e">

而出现在了:
<img width="237" alt="图片" src="https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/2bcdb2b1-9587-478c-a52f-152c46302904">

并且这个出现的问题发生在 点击消息后(~~具体复现方式不明, 有几率~~ 右键, 然后立即点击左下角菜单), 在左下角菜单中出现.

在最新版的 Windows 上不会复现上述问题.

版本:
<img width="608" alt="图片" src="https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/7d7c9b6b-a293-4938-ac34-c251399988b1">

**Comment by MUKAPP** [comment]
你有时间看一下最新的代码有没有解决

**Comment by tiankaima** [comment]
> 你有时间看一下最新的代码有没有解决

Works, thx.

这个要不要也改一下)
```js
const qContextMenu = document.querySelector("div.q-context-menu:not(.more-menu)");
```

**Comment by MUKAPP** [comment]
> 这个要不要也改一下)
> ```js
> const qContextMenu = document.querySelector("div.q-context-menu:not(.more-menu)");
> ```

现在应该不会在其他地方添加了吧
理论上（）

**Comment by tiankaima** [comment]
哦不过 innerText 多了 「正在翻译」

<img width="324" alt="图片" src="https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/1dcfd4c3-e924-4568-9ca9-9b7b639a20ce">

![图片](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/8f72c147-5898-461f-bd50-41d835ea4ce7)


....

**Comment by tiankaima** [comment]
> > 这个要不要也改一下)
> > ```js
> > const qContextMenu = document.querySelector("div.q-context-menu:not(.more-menu)");
> > ```
> 
> 现在应该不会在其他地方添加了吧 理论上（）

在说这个 
https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/pull/7#discussion_r1553319484

左下角这个 More panel 也用了一样的 id
不过现在确实正常就是了(x

**Comment by MUKAPP** [comment]
> 哦不过 innerText 多了翻译两个字
> 
> <img width="324" alt="图片" src="https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/1dcfd4c3-e924-4568-9ca9-9b7b639a20ce">
> 
> ![图片](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/8f72c147-5898-461f-bd50-41d835ea4ce7)
> 
> 
> ....

多了“

正在翻译？”

**Comment by MUKAPP** [comment]
> 不过现在确实正常就是了(x

很多菜单的class都是q-context-menu，之前加过处理了，所以其他地方没问题的话这里肯定是不会有问题的（）

**Comment by tiankaima** [comment]
> > 哦不过 innerText 多了翻译两个字
> 多了“
> 
> 正在翻译？”

~~要不直接 `.split("\n")[:-1]` 吧~~ 实在是js苦手看不懂……

**Comment by MUKAPP** [comment]
> ~要不直接 `.split("\n")[:-1]` 吧~ 实在是js苦手看不懂……

有点怪的，我那会儿好像没遇到这问题
明天再看看吧（）

**Comment by MUKAPP** [comment]
好了

**Comment by tiankaima** [comment]
<img width="251" alt="图片" src="https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/a85cc9b3-1527-41bc-87b4-33f020cec8be">

不过这个好像是deeplX崩了

**Comment by MUKAPP** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/41848070/9141a090-a9ab-444b-8f20-79f9d90e2b2e)
应该是被deepl拦了，有能力还是自己搭吧，云端或者本地搭都可以

**Comment by tiankaima** [comment]
> ![image](https://private-user-images.githubusercontent.com/41848070/320187537-9141a090-a9ab-444b-8f20-79f9d90e2b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODU3NjEsIm5iZiI6MTcxMjM4NTQ2MSwicGF0aCI6Ii80MTg0ODA3MC8zMjAxODc1MzctOTE0MWEwOTAtYTlhYi00NDRiLThmMjAtNzlmOWQ5MGUyYjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA2Mzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYzgzNGY1YTQxMWRiOTAxMTYzNWJhNjQzOTZkNjNhOWJmZDE0NDlhNzI5YmQyZTc2ZmJiMzUzZDAyNjlmYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RgpSl160fn3LfaUX0ltjBAjLJfGeoUBZxFxYjypkedk) 应该是被deepl拦了，有能力还是自己搭吧，云端或者本地搭都可以

OK部署了  `https://deeplx.tiankaima.dev` :)

**Comment by MUKAPP** [comment]
我看看插件有没有办法在本地搞一个

**Comment by tiankaima** [comment]
<img width="202" alt="图片" src="https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/91816094/b605903e-9eea-4a4c-b71b-8e4557d0f623">

不过 翻译的问题好像还没解决 (x

**Comment by MUKAPP** [comment]
你更新了吗？
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/41848070/1dc6607d-6833-4d06-b58e-c61177034ce8)

**Comment by tiankaima** [comment]
sorry改错文件了 我的问题🙇🙇🙇🙇
本地又拉了遍repo 来 PR, vscode开错东西了) 🙇🙇🙇🙇

ok现在好了 非常感谢🙏
