### ISSUE TITLE
翻译按钮出现异常

### ISSUE THREAD

**Issue by Starrain08** [MUKAPP/LiteLoaderQQNT-DeepL#9]
如题，qqnt运行一段时间后，聊天栏翻译按钮出现异常
![image](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/119772101/92a9b15c-33bd-4a93-84d2-4d9cf2e5889c)

**Comment by MUKAPP** [comment]
我之前也遇到了，但是不知道怎么触发的，还修不了

**Comment by SoudayoWwww** [comment]
> 我之前也遇到了，但是不知道怎么触发的，还修不了

我复现了，从侧边栏的`主页面按钮`界面切换到`联系人按钮`界面再切回来就会触发，之后在两个按钮之间来回点，点的次数越多DeepL图标出的越多

![1](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL/assets/52328223/e327d187-9c39-43db-a717-16d716794c55)

**Comment by siyue2016** [comment]
我也触发了

**Comment by MUKAPP** [comment]
已修复
